name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and Android SDK (cmdline-tools)
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk python3-pip git wget

          # Set up folders
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools

          # Download and unzip cmdline-tools into temp folder
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
          unzip tools.zip -d cmdline-tools-temp

          # Move files into proper 'latest' folder
          mkdir -p latest
          mv cmdline-tools-temp/* latest/

          # Accept licenses
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

          # Install required SDK packages
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/.buildozer/android/platform/android-sdk "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Install Buildozer and Build APK
        run: |
          pip install --upgrade pip
          pip install buildozer cython
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wordle-app-apk
          path: bin/*.apk
