name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and build APK
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk python3-pip git wget
          pip install buildozer cython

          # Accept all Android SDK licenses
          mkdir -p "$HOME/.android"
          touch "$HOME/.android/repositories.cfg"
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$HOME/.android/repositories.cfg"

          # Remove broken build-tools to force proper reinstall
          rm -rf ~/.buildozer/android/platform/android-sdk/build-tools

          # Install Apache Ant manually (needed for Kivy builds)
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.zip
          unzip apache-ant-1.9.4-bin.zip
          export ANT_HOME=$PWD/apache-ant-1.9.4
          export PATH=$ANT_HOME/bin:$PATH

          # Build the APK
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wordle-app-apk
          path: bin/*.apk
