name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and build APK
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk python3-pip git wget
          pip install buildozer cython

          # Accept all SDK licenses (bypasses interactive prompts)
          mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg

          # Manually create license file with Google's hash
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

          # Install Apache Ant
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.zip
          unzip apache-ant-1.9.4-bin.zip
          export ANT_HOME=$PWD/apache-ant-1.9.4
          export PATH=$ANT_HOME/bin:$PATH

          # Clean up old or broken build tools
          rm -rf ~/.buildozer/android/platform/android-sdk/build-tools

          # Build APK
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wordle-app-apk
          path: bin/*.apk
